#### 리턴 타입이 `void`인 메소드의 예외 발생 상황을 모의 객체로 나타내기
- 다음 메소드의 `NoSuchUserException` 예외 발생 상황을 테스트하려고 했다.

```
public void loginUser(LoginUserRequest request, HttpSession session) {
  	User user = userMapper.findUserByEmail(request.getEmail()).orElseThrow(() -> {
  		throw new NoSuchUserException("등록된 사용자가 아닙니다");
  	});

  	if (!request.getPassword().equals(user.getPassword())) {
  		throw new PasswordNotMatchException("비밀번호가 다릅니다");
  	}

  	session.setAttribute("user", request);
  }
```

- 문제는 `loginUser` 메소드의 리턴 타입이 `void`인데 `when...thenThrow`로는 예외를 내는 상황을 모의 객체로 나타낼 수 없다는 것이다.
- 해결할 수 있는 방법은 doThrow를 쓰는 것이다.
```
  @Test
  @DisplayName("등록된 사용자이더라도 비밀번호 틀리면 로그인 불가")
  public void loginFailPasswordNotMatch() throws Exception {
  	// 테스트 데이터 정의...

  	doThrow(PasswordNotMatchException.class).when(userService)
  		.loginUser(any(LoginUserRequest.class), any(HttpSession.class));

  	// 실행...
  	mockMvc.perform(post("/users/login")...

  	// 행위 검증
  	assertThrows(PasswordNotMatchException.class, () -> {
  		userService.loginUser(invalidRequest, session);
  	});

  	verify(userService, times(2)).loginUser(any(LoginUserRequest.class),
  		any(HttpSession.class));
  }
```

- 지난번에 알아낸 `doNothing`과 비슷한 역할을 하는 것 같다.
